# Generated by Django 4.2.1 on 2023-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.PositiveIntegerField(choices=[(0, 'Cliente'), (1, 'Desenvolvedor')], default=0),
        ),
    ]
